#services:
#  zakupkiparser:
#    image: zakupkiparser
#    build:
#      context: .
#      dockerfile: Dockerfile

version: '3.8'

services:
  mongo:
    image: mongo:5.0.15
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "55555:27017"
    volumes:
      - '.private/mongo_data:/var/lib/mongodb'


